# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
