# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0002_articles_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=250)),
                ('journal', models.CharField(max_length=250)),
                ('abstract', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.DeleteModel(
            name='Abstracts',
        ),
    ]
