# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0003_auto_20170904_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=50)),
                ('gene_abb', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation', models.CharField(max_length=100)),
                ('pathway', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='article',
            name='variation',
        ),
    ]
